## Globals

In [8]:
import numpy as np
no_of_users = 3
no_of_items = 3

In [103]:
# #get trust factors
# trust = []
# for i in range(no_of_users**2):
#     temp = input()
#     trust.append(temp)
# print trust
trust = [1,0.1,1,0.7,1,0.3,1,0.2,1]   #initial trust of users on one another
trust = np.array(trust).reshape(3,3)
print 'Initial trust of users on one another','\n',trust
ratings = [4,5,2,4,3,5,5,4,5]       #actual ratings of users
ratings = np.array(ratings).reshape(3,3)
print 'Actual ratings of users','\n',ratings

Initial trust of users on one another 
[[ 1.   0.1  1. ]
 [ 0.7  1.   0.3]
 [ 1.   0.2  1. ]]
Actual ratings of users 
[[4 5 2]
 [4 3 5]
 [5 4 5]]


In [104]:
reference_world = np.ones((no_of_users,no_of_users,no_of_users))    #matrix for storing the rating world from different person views
# print reference_world
for k in range(no_of_users):
    reference_world[k] = trust
for k in range(no_of_users):
    for i in range(no_of_users): 
        for j in range(no_of_users):
                if(j==k or i==k):
                    pass
                else:
                    reference_world[k][i][j] = reference_world[k][i][j]*trust[k][i]
print reference_world

[[[ 1.    0.1   1.  ]
  [ 0.7   0.1   0.03]
  [ 1.    0.2   1.  ]]

 [[ 0.7   0.1   0.7 ]
  [ 0.7   1.    0.3 ]
  [ 0.3   0.2   0.3 ]]

 [[ 1.    0.1   1.  ]
  [ 0.14  0.2   0.3 ]
  [ 1.    0.2   1.  ]]]


In [105]:
reference_ratings = np.zeros((no_of_users,no_of_users,no_of_items))   #matrix for storing the rating world from different person views
for k in range(no_of_users):
    reference_ratings[k] = ratings
# print reference_ratings
for k in range(no_of_users):
    for i in range(no_of_users): 
        for j in range(no_of_items):
                if(i==k):
                    pass
                else:
                    reference_ratings[k][i][j] = reference_ratings[k][i][j]*trust[k][i]
print reference_ratings

[[[ 4.   5.   2. ]
  [ 0.4  0.3  0.5]
  [ 5.   4.   5. ]]

 [[ 2.8  3.5  1.4]
  [ 4.   3.   5. ]
  [ 1.5  1.2  1.5]]

 [[ 4.   5.   2. ]
  [ 0.8  0.6  1. ]
  [ 5.   4.   5. ]]]


In [106]:
dev_ratings = ratings*3-reference_ratings.sum(axis=0)
print dev_ratings

[[ 1.2  1.5  0.6]
 [ 6.8  5.1  8.5]
 [ 3.5  2.8  3.5]]


In [107]:
dev_trust = trust*3 - reference_world.sum(axis=0)
print dev_trust

[[ 0.3   0.    0.3 ]
 [ 0.56  1.7   0.27]
 [ 0.7   0.    0.7 ]]


### another with 5 user

In [108]:
no_of_users = 5
no_of_items = 3

In [120]:
# #get trust factors
# trust = []
# for i in range(no_of_users**2):
#     temp = input()
#     trust.append(temp)
# print trust
trust = [1,0.1,1,0.7,0.8,0.7,1,0.3,0.5,0.5,1,0.2,1,0.7,0.7,0.7,0.3,0.9,1,0.8,0.9,0.1,0.8,0.6,0.6]   #initial trust of users on one another
trust = np.array(trust).reshape(no_of_users,no_of_users)
print 'Initial trust of users on one another','\n',trust
ratings = [4,5,0,0,3,5,5,0,5,4,4,5,3,5,4]       #actual ratings of users
ratings = np.array(ratings).reshape(no_of_users,no_of_items)
print 'Actual ratings of users','\n',ratings

Initial trust of users on one another 
[[ 1.   0.1  1.   0.7  0.8]
 [ 0.7  1.   0.3  0.5  0.5]
 [ 1.   0.2  1.   0.7  0.7]
 [ 0.7  0.3  0.9  1.   0.8]
 [ 0.9  0.1  0.8  0.6  0.6]]
Actual ratings of users 
[[4 5 0]
 [0 3 5]
 [5 0 5]
 [4 4 5]
 [3 5 4]]


In [121]:
reference_world = np.ones((no_of_users,no_of_users,no_of_users))    #matrix for storing the rating world from different person views
# print reference_world
for k in range(no_of_users):
    reference_world[k] = trust
for k in range(no_of_users):
    for i in range(no_of_users): 
        for j in range(no_of_users):
                if(j==k or i==k):
                    pass
                else:
                    reference_world[k][i][j] = reference_world[k][i][j]*trust[k][i]
print reference_world

[[[ 1.    0.1   1.    0.7   0.8 ]
  [ 0.7   0.1   0.03  0.05  0.05]
  [ 1.    0.2   1.    0.7   0.7 ]
  [ 0.7   0.21  0.63  0.7   0.56]
  [ 0.9   0.08  0.64  0.48  0.48]]

 [[ 0.7   0.1   0.7   0.49  0.56]
  [ 0.7   1.    0.3   0.5   0.5 ]
  [ 0.3   0.2   0.3   0.21  0.21]
  [ 0.35  0.3   0.45  0.5   0.4 ]
  [ 0.45  0.1   0.4   0.3   0.3 ]]

 [[ 1.    0.1   1.    0.7   0.8 ]
  [ 0.14  0.2   0.3   0.1   0.1 ]
  [ 1.    0.2   1.    0.7   0.7 ]
  [ 0.49  0.21  0.9   0.7   0.56]
  [ 0.63  0.07  0.8   0.42  0.42]]

 [[ 0.7   0.07  0.7   0.7   0.56]
  [ 0.21  0.3   0.09  0.5   0.15]
  [ 0.9   0.18  0.9   0.7   0.63]
  [ 0.7   0.3   0.9   1.    0.8 ]
  [ 0.72  0.08  0.64  0.6   0.48]]

 [[ 0.9   0.09  0.9   0.63  0.8 ]
  [ 0.07  0.1   0.03  0.05  0.5 ]
  [ 0.8   0.16  0.8   0.56  0.7 ]
  [ 0.42  0.18  0.54  0.6   0.8 ]
  [ 0.9   0.1   0.8   0.6   0.6 ]]]


In [122]:
reference_ratings = np.zeros((no_of_users,no_of_users,no_of_items))   #matrix for storing the rating world from different person views
for k in range(no_of_users):
    reference_ratings[k] = ratings
# print reference_ratings
for k in range(no_of_users):
    for i in range(no_of_users): 
        for j in range(no_of_items):
                if(i==k):
                    pass
                else:
                    reference_ratings[k][i][j] = reference_ratings[k][i][j]*trust[k][i]
print reference_ratings

[[[ 4.   5.   0. ]
  [ 0.   0.3  0.5]
  [ 5.   0.   5. ]
  [ 2.8  2.8  3.5]
  [ 2.4  4.   3.2]]

 [[ 2.8  3.5  0. ]
  [ 0.   3.   5. ]
  [ 1.5  0.   1.5]
  [ 2.   2.   2.5]
  [ 1.5  2.5  2. ]]

 [[ 4.   5.   0. ]
  [ 0.   0.6  1. ]
  [ 5.   0.   5. ]
  [ 2.8  2.8  3.5]
  [ 2.1  3.5  2.8]]

 [[ 2.8  3.5  0. ]
  [ 0.   0.9  1.5]
  [ 4.5  0.   4.5]
  [ 4.   4.   5. ]
  [ 2.4  4.   3.2]]

 [[ 3.6  4.5  0. ]
  [ 0.   0.3  0.5]
  [ 4.   0.   4. ]
  [ 2.4  2.4  3. ]
  [ 3.   5.   4. ]]]


In [123]:
dev_ratings = ratings*no_of_users-reference_ratings.sum(axis=0)
print dev_ratings

[[  2.8   3.5   0. ]
 [  0.    9.9  16.5]
 [  5.    0.    5. ]
 [  6.    6.    7.5]
 [  3.6   6.    4.8]]


In [124]:
dev_trust = trust*no_of_users - reference_world.sum(axis=0)
print dev_trust

[[ 0.7   0.04  0.7   0.28  0.48]
 [ 1.68  3.3   0.75  1.3   1.2 ]
 [ 1.    0.06  1.    0.63  0.56]
 [ 0.84  0.3   1.08  1.5   0.88]
 [ 0.9   0.07  0.72  0.6   0.72]]


## Filmtrust data

In [23]:
ratings = np.zeros((1508,2071))
with open('ratings.txt','r') as f:
    for line in f:
        line = line.split()
        i = int(line[0])
        j = int(line[1])
        ratings[i-1][j-1] = float(line[2])
print ratings

[[ 2.   4.   3.5 ...,  0.   0.   0. ]
 [ 0.   0.   0.  ...,  0.   0.   0. ]
 [ 0.   0.   0.  ...,  0.   0.   0. ]
 ..., 
 [ 0.   0.   0.  ...,  0.   0.   0. ]
 [ 0.   4.   0.  ...,  0.   0.   0. ]
 [ 1.5  3.   2.  ...,  0.   0.   0. ]]


In [ ]:
trust = np.zeros((1508,2071))
with open('trust.txt','r') as f:
    for line in f:
        line = line.split()
        i = int(line[0])
        j = int(line[1])
        ratings[i-1][j-1] = float(line[2])
print ratings
